trigger:
- DucTestBuild

pool: my-personal-computer

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**/SeniorConnect.sln'
  project: '**/SeniorConnect.csproj'

steps:

- task: UseDotNet@2
  displayName: 'Install .Net SDK version'
  inputs:
    packageType: sdk
    version: 8.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet
- task: NuGetToolInstaller@1
  displayName: 'NuGet Tool Installer'

- task: NuGetCommand@2
  name: 'NuGetRestore'
  displayName: 'NuGet Restore Packages'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'


# Uncomment this section to run tests later
#- task: DotNetCoreCLI@2
#  displayName: 'Run Tests'
#  inputs:
#    command: 'test'
#    projects: '$(solution)'
#    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'SeniorConnectArtifact'
    publishLocation: 'Container'
